### ISSUE TITLE
Optimized benchmark using for loop?

### ISSUE THREAD

**Issue by proyb6** [drujensen/fib#111]
For-loop could be benchmark on top of the memoized version.

Based on https://github.com/T-PWK/go-fibonacci/blob/master/fib.go
```
import (
  "fmt"
)

func main() {
  fmt.Println("46 is  ", fib(46))
}

func fib(n uint) uint64 {
  if n <= 1 {
    return uint64(n)
  }

  var n2, n1 uint64 = 0, 1
  for i := uint(2); i < n; i++ {
    n2, n1 = n1, n1+n2
  }
  return n2 + n1
}
```

**Comment by drujensen** [comment]
Hi @proyb6 Thanks for your comment.  

There are several examples using a loop instead of a recursive call in the `optimized` folder. 

If you want, you may submit a PR.
