### ISSUE TITLE
Much faster version for Julia, using the same algorithm but with proper coding.

### ISSUE THREAD

**Issue by skanskan** [drujensen/fib#113]
The Julia solution hasn't been optimized, as with other languages.

This code, created by Tamas_Papp, is much faster while using the same algorithm:
https://discourse.julialang.org/t/simple-recursive-fibonaci-example-how-to-make-it-faster/32369/14
Could you please update the fib.jl file with it, please?

```
function fibval(::Val{N}) where N
    if N ≤ 1
        1
    else
        fibval(Val{N - 1}()) + fibval(Val{N - 2}())
    end
end
```

Other solutions are also faster:
For example, this one created by DNF. But it uses an external package for memoization.

```
@memoize function fibmem(n)
         if n <= 1 return 1 end
         return fibmem(n - 1) + fibmem(n - 2)
       end

```

**Comment by drujensen** [comment]
Hi @skanskan Thanks for your comment.  

All languages can optimize the fib recursive code to make them faster.  That is not the point of this project. The main point of this project is to see how different languages handle the same recursive code (or at least as close as possible).  

Both of these solutions can be submitted to the optimized versions if you want to provide a PR.

**Comment by skanskan** [comment]
Though the code being used for the different languages isn't the same, for example the C version predeclares the variable as Int64, but you are not doing the same with the Julia code. It's not fair to compare an optimized C code vs a non-optimized Julia code.

That's why I'm not changing the algorithm but just specializing the variable declaration, using the same code.

**Comment by drujensen** [comment]
I see.

It’s fine to declare types as most languages require them.  Please submit a PR and we can request a review from other devs that know Julian.

**Comment by flip111** [comment]
@skanskan i would also be interesting to see the specialized version compiled.
