### ISSUE TITLE
dotnet run defaults to debug mode

### ISSUE THREAD

**Issue by ncsurfus** [drujensen/fib#12]
The csharp (dotnet core) should probably be ran with dotnet run -c release. That’s likely why it’s so much slower than msc/java.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21

It might also be better to use dotnet build -c release, and then run it with dotnet fib.dll (to be comparable to the java/msc)... the fastest dotnet solution would likely be dotnet publish -c release -r osx-x64 and then run ./fib in the output directory.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by hex11** [comment]
And these are what `dotnet run` do:
1) restore (since dotnet core 2.0)
2) build
3) initialize runtime
4) actually run 'fib'

It's not fair that the C# test counts the time from 1 to 4 while the Java test counts from 3 to 4.

**Comment by grapehunter** [comment]
@ncsurfus @hex11 
I have opened a pull request #16 to resolve this issue

**Comment by drujensen** [comment]
I've addressed the compilation issue and defaulted to use TCO.  Thanks for the updates!
