### ISSUE TITLE
Pypy benchmark for python

### ISSUE THREAD

**Issue by MonliH** [drujensen/fib#125]
It would be nice if there were a [`pypy`](https://www.pypy.org/) benchmark here, too. Pypy aims to be faster than the normal CPython implementation by JIT compiling the code. In my tests, this benchmark is significantly faster than vanilla CPython:

```bash
$ time python fib.py  # CPython implementation
2971215073
_________________________
Executed in  630.05 secs
   usr time  627.57 secs
   sys time    0.21 secs

$ time pypy fib.py  # Pypy
2971215073
_________________________
Executed in   33.43 secs
   usr time   33.31 secs
   sys time    0.05 secs
```

As shown, pypy is almost 19x faster on my machine!

**Comment by machitgarha** [comment]
I confirm this, getting the same results.

However, I think this repository aims to compare language run-times, not the performance of interpreters or compilers. I totally am interested in having such a thing, but that would expand the results a lot, which requires a bit of extra work. As an example, consider C++: We have at least four different compilers (GCC, Clang/LLVM, Intel's, MSVC, etc.).

**Comment by MonliH** [comment]
> compare language run-times

I mean, languages technically *don't* have runtimes, only the implementations do. 

But, yeah, it would be a lot of work to include all the the compiliers for every language. However, the c++ compilers are probably around the same in terms of performance for the fib benchmark (maybe we should test that!). In the case of pypy though, the difference in performance so crazy (i.e., ~19x faster) that it's probably worth adding.

**Comment by machitgarha** [comment]
> > compare language run-times
>
> I mean, languages technically _don't_ have runtimes, only the implementations do.

Right.
 
> But, yeah, it would be a lot of work to include all the the compiliers for every language. However, the c++ compilers are probably around the same in terms of performance for the fib benchmark (maybe we should test that!). In the case of pypy though, the difference in performance so crazy (i.e., ~19x faster) that it's probably worth adding.

You're right, but C++ was only an example.

By the way, I agree with you. Why not opening a PR? The change would be minimal.

**Comment by MonliH** [comment]
Yeah, I'll open a PR. Not sure why I didn't do that to begin with :facepalm:.
