### ISSUE TITLE
Compiler flag for rustc "-C lto=fat" not necessary and slows down execution

### ISSUE THREAD

**Issue by benjaminbolbrinker** [drujensen/fib#127]
Hi,
according to the official docs (https://doc.rust-lang.org/rustc/codegen-options/index.html) the compiler flag "lto=fat" is used for "attempts to perform optimizations across all crates within the dependency graph".
I expected Rust to be 'more comparable' with respect to speed compared to C and C++. 
I did some testing and figured out that for this example (calculation of Fibonacci numbers) the execution is slowed down quite a bit by using this compiler flag.

I think it would be fair to delete the part "-C lto=fat" from "rustc -C opt-level=3 -C lto=fat fib.rs" in the "run.rb" file.

**Comment by drujensen-happymoney** [comment]
Hi @benjaminbolbrinker Sounds fair.  Can you provide a PR?
