### ISSUE TITLE
some languages are with TCO but test case not implemented properly

### ISSUE THREAD

**Issue by AmmRage** [drujensen/fib#13]
for the list of languages, please ref https://en.wikipedia.org/wiki/Tail_call.

it's not fair for those.

**Comment by drujensen** [comment]
@AmmRage can you identify which languages are using this technique?

**Comment by drujensen** [comment]
I've added a note that Go and Swift do not seem to use this optimization.  If you can help identify others, let me know.

**Comment by jbakic** [comment]
Don't know if it matters any more, but none of the programs I see here can even use the tail-call optimization, because the last call the fib function makes is the "+" operator. Similar to the first example here: https://en.wikipedia.org/wiki/Tail_call#Example_programs -- they cannot be TCOed.
