### ISSUE TITLE
Implement all languages mentioned in the song "Write in C"

### ISSUE THREAD

**Issue by autinerd** [drujensen/fib#135]
[This song](https://www.youtube.com/watch?v=1S1fISh-pag) based of "Let it be" mentions some old languages, it would be cool to have fib implemented in all of these languages, if possible.

- [x] C
- [X] Lisp
- [x] FORTRAN
- [x] Assembler
- [ ] BASIC
- [X] Pascal
- [x] COBOL
- [ ] PL/I
- [x] Ada

**Comment by drujensen** [comment]
Lol.  Yes, that would be very cool.  

Looks like you can install a basic interpreter using `sudo apt-get install bwbasic`
