### ISSUE TITLE
Memoized lisp code can be better

### ISSUE THREAD

**Issue by francogrex** [drujensen/fib#138]
;;This in common lisp is the fastest there is, nanoseconds and can compute fib n > 200
(defun fib (n)
  (labels ((fib* (xno x-2 x-1)
             (if (= xno n)
                 (+ x-2 x-1)
                 (fib* (1+ xno) x-1 (+ x-1 x-2)))))
    (fib* 0 1 0)))

(time (fib 46))

;; Evaluation took:
;;   0.000 seconds of real time
;;   0.000000 seconds of total run time (0.000000 user, 0.000000 system)
;;   100.00% CPU
;;   9,520 processor cycles
;;   0 bytes consed
  
;; 2971215073

**Comment by dkochmanski** [comment]
the first version is recursive going bottom->top, the second version is memoized. both handle arbitrary n (memoized version is limited by the stack limit (n) and the array size limit).

```common-lisp
(defun fib (n)
  (labels ((fib* (xno x-2 x-1)
             (if (= xno n)
                 (+ x-2 x-1)
                 (fib* (1+ xno) x-1 (+ x-1 x-2)))))
    (if (<= n 1)
        n
        (fib* 2 0 1))))

(defun fib-memoized (n)
  (let ((memo (make-array (1+ n) :initial-element nil)))
    (labels ((memofib (n)
               (or (aref memo n)
                   (setf (aref memo n)
                         (if (<= n 1)
                             n
                             (+ (memofib (- n 1))
                                (memofib (- n 2))))))))
      (memofib n))))
```

**Comment by francogrex** [comment]
dkochmanski commented Jul 19, 2021, is the correct code, fastest again. My contribution above is not the right mathematical fib function and as issues #37 explained, it is rather a code copied from the readme file which does not specify the correct code, because this: (return 1 if n <= 1) ... is not a good specification, because fib of 46 is not 2971215073
