### ISSUE TITLE
Perl performance using a fib.c as a shared library

### ISSUE THREAD

**Issue by richieri** [drujensen/fib#147]
Not an issue at all, but a test I made since IMHO, Perl shouldn't be used in situations where we need a complex or long calculation.

So, the original result for Perl to execute the code is 1085 seconds. Using fib as a C function, it decreases to 25 seconds.

How to reproduce:

Create a fib.c with the following content:

```
#include <stdio.h>
#include <stdint.h>

uint64_t fib(uint64_t n) {
  if (n <= 1) return n;
  return fib(n - 1) + fib(n - 2);
}
```

Compile it with
`cc -shared -o fib.so fib.c `

Create a perl file with this content:
```
use FFI::Platypus 2.00;
use FFI::CheckLib qw( find_lib_or_die );
use File::Basename qw( dirname );

my $ffi = FFI::Platypus->new( api => 2, lib => './fib.so' );
$ffi->attach( fib => ['uint64_t'] => 'uint64_t' );

print fib(47);
```

Solve those perl dependencies before executing (FFI::Platypus and others that may appear)

**Comment by drujensen** [comment]
Thanks for sharing this solution.  You can find other solutions like this in the `optimized` folder.  I'm open to a PR if you want to add this solution to that folder.
