### ISSUE TITLE
uint32 vs uint64 inconsistency

### ISSUE THREAD

**Issue by mratsim** [drujensen/fib#19]
Some languages are using uint32

https://github.com/drujensen/fib/blob/daa6006bf8e874367a2c4ccf444442464f244bdd/fib-mem.go#L7

https://github.com/drujensen/fib/blob/daa6006bf8e874367a2c4ccf444442464f244bdd/fib.cr#L1

while others are using uint64 types.

Edit: not sure about `long` in C/C++/D

**Comment by drujensen** [comment]
fixed and benchmarks updated.

**Comment by mratsim** [comment]
In C/C++/D you should also use longlong instead of long to ensure 64-bit That might be why Nim is so much faster. C/C++ would need to zero-extend the argument every-time they enter the function and add additional logic to only take the low part after computation.
