### ISSUE TITLE
Why no-prepopulate-passes in Rust?

### ISSUE THREAD

**Issue by JordiPolo** [drujensen/fib#2]
Currently Rust is compiled with the `no-prepopulate-passes` option.

This prevents LLVM to run an optimization pass which probably compilers of the other languages do run so it seems an unfair disadvantage for Rust.

I would suggest to just do 
`rustc -O fib.rs`

or to keep it in line with the options for C/C++ do:
`rustc -C opt-level=3 fib.rs`

(I did not see any performance difference between those two above options)

I am not submitting the PR because I think the change should come with the new performance numbers which I can not run as my hardware setup is different from yours.

**Comment by drujensen** [comment]
Thanks @JordiPolo for reporting this.  I have made the change.

**Comment by JordiPolo** [comment]
Thanks!
