### ISSUE TITLE
C# benchmark uses .NET SDK 2.0

### ISSUE THREAD

**Issue by Sebazzz** [drujensen/fib#22]
I'm not sure whether it has an impact on the time, but the C# benchmark uses the .NET 2.0 Core SDK [instead of .NET 2.1 SDK], possiblity causing some compatibility flags to be enabled. 

See: https://github.com/drujensen/fib/blob/master/fib.csproj

**Comment by lwansbrough** [comment]
It’s using .NET Core 2.0 not .NET 2.0. The former being very recent.

**Comment by Sebazzz** [comment]
Typo, I meant .NET Core 2.0 SDK.

**Comment by lwansbrough** [comment]
Ah sorry, yes 2.1 would be interesting given its considerable performance improvements (though I’m not sure how relevant those improvements would be to this benchmark.)

**Comment by drujensen** [comment]
updated to 2.2.15 on ubuntu docker image
