### ISSUE TITLE
This includes startup times

### ISSUE THREAD

**Issue by Dobatymo** [drujensen/fib#25]
This does not accuratly measure the performance as startup times are included.
Also Python is compiled to bytecode before execution (which is also included in the startup time)

**Comment by deckar01** [comment]
It is accurate for users who run scripts individually, which is not uncommon. The majority of the "Interpreted, dynamically typed" languages are run as a daemon in a web server in practice. I wonder if there is a simple way to benchmark these scripts with `time` as a warm process without introducing the overhead of network requests.

**Comment by drujensen** [comment]
@Dobatymo This is correct.  Some languages do have a start up time cost.  This is apart of the benchmark.  I have included a note in the readme to keep that in mind.
