### ISSUE TITLE
Recursive, iterative or tail-recursive?

### ISSUE THREAD

**Issue by tgulacsi** [drujensen/fib#34]
Memoization is included in the benchmark, but iterative algorithm is not.

What is this benchmark measuring?

See https://medium.com/@felipedutratine/iterative-vs-recursive-vs-tail-recursive-in-golang-c196ca5fd489

The algorithm is more important than the language/runtime...

**Comment by drujensen** [comment]
Hi @tgulacsi This was just a fun project I created to demonstrate how Crystal compared to the top languages used on github.  It was for a presentation I did at a meet up.

An iterative algorithm is another way to perform the same calculation but that was never the point of this exercise. 

The breaking examples were never really meant to compare languages performance, only that there are ways to make the recursive call faster with minimal changes.  Some of these examples seem to have gotten out of hand with not so minimal changes.

**Comment by OvermindDL1** [comment]
As a note, the front readme states:

> NOTE: Swift and Go do not seem to use Tail Call Optimization so this may be why they are showing up as twice as slow. Thank you Ammrage for pointing this out.

However, none of the `fib` algorithm used in any of the main benchmarks are TCO'able because the `+` is in tail call position, so I'm unsure if this statement makes sense on the readme.

**Comment by drujensen** [comment]
Interesting.  Ok, I will remove this note.

**Comment by tgulacsi** [comment]
Thanks for the clarification!
