### ISSUE TITLE
Swift: disable runtime safety checks

### ISSUE THREAD

**Issue by RuiCarneiro** [drujensen/fib#35]
Other languages either don't have those safety checks or have them disabled, so Swift should also have them disabled, in my machine, it cut 33% of the execution time.

    $ swiftc -O -g Fib.swift && hyperfine ./Fib
    Benchmark #1: ./Fib
    
      Time (mean ± σ):      9.750 s ±  0.006 s    [User: 9.732 s, System: 0.008 s]
     
      Range (min … max):    9.741 s …  9.758 s

To

    $ swiftc -O -Ounchecked -g Fib.swift && hyperfine ./Fib
    Benchmark #1: ./Fib
    
      Time (mean ± σ):      6.407 s ±  0.006 s    [User: 6.393 s, System: 0.007 s]
     
      Range (min … max):    6.398 s …  6.419 s

**Comment by weissi** [comment]
I think running with `-Ounchecked` isn't a great idea but we can achieve the same effect in a better way: In the particular program, we know that there won't be any integer over- or underflows so we should just replace `+` with `&+` and `-` with `&-` which tells the Swift compiler that we don't want to trap on over/underflows and therefore it won't emit the checks and the performance should be of `-O` should be on par with `-Ounchecked`.

**Comment by drujensen** [comment]
Hi @RuiCarneiro. I have never disabled these runtime checks for my iOS apps.  I think we should keep this as is.  Maybe we can make a note that some of the compiled languages are not providing these safety checks.  WDYT?

**Comment by weissi** [comment]
@RuiCarneiro / @drujensen why not just use the `&-` and `&+` operators instead of `-` and `+`? That way you'll get the same performance as `-Ounchecked` with `-O`. In this case it's the right choice as we know it won't under/overflow.

**Comment by RuiCarneiro** [comment]
> @RuiCarneiro / @drujensen why not just use the `&-` and `&+` operators instead of `-` and `+`? That way you'll get the same performance as `-Ounchecked` with `-O`. In this case it's the right choice as we know it won't under/overflow.

Yeah, I think it's a valid option.

**Comment by drujensen** [comment]
@RuiCarneiro ok, i will make that change.  thx.

**Comment by RuiCarneiro** [comment]
I think I should close it then.

**Comment by RuiCarneiro** [comment]
I think I should close it then.
