### ISSUE TITLE
python fib wrong result and misleading

### ISSUE THREAD

**Issue by intha** [drujensen/fib#37]
```
def fib(n):
  if n <= 1: return 1
  return fib(n - 1) + fib(n - 2)

print(fib(34))
```

gives 9227465, however it's 5702887

**Comment by intha** [comment]
Well, I tries examples in python 3, and found your calculations misleading as you took very bad example of recursion:

import time;
ticks = time.time()

## Example 1: Using looping technique (1 ms!)
def fib(n):
 a,b = 1,1
 for i in range(n-1):
  a,b = b,a+b
 return a
print('Ex1 ' + str(fib(46)))
print(time.time() - ticks)
ticks = time.time()

## Example 2: Using recursion (takes a lot of time, probably 700 sec )
def fibR(n):
 if n==1 or n==2:
  return 1
 return fibR(n-1)+fibR(n-2)
print ('Ex2 ' + str(fibR(6)))
print(time.time() - ticks)
ticks = time.time()

## Example 4: Using memoization (0 ms!)
def memoize(fn, arg):
 memo = {}
 if arg not in memo:
  memo[arg] = fn(arg)
  return memo[arg]
 
## fib() as written in example 1.
fibm = memoize(fib,46)
print ('Ex4 ' + str(fibm))
print(time.time() - ticks)
ticks = time.time()

## Example 5: Using memoization as decorator (0 ms!)
class Memoize:
 def __init__(self, fn):
  self.fn = fn
  self.memo = {}
 def __call__(self, arg):
  if arg not in self.memo:
   self.memo[arg] = self.fn(arg)
   return self.memo[arg]
 
@Memoize
def fib(n):
 a,b = 1,1
 for i in range(n-1):
  a,b = b,a+b
 return a
print ('Ex5 ' + str(fib(46)))
print(time.time() - ticks)
ticks = time.time()

**Comment by drujensen** [comment]
@intha We are using the second example you provided for comparison with other languages:
```
def fib(n):
 if n==1 or n==2:
  return 1
 return fib(n-1) + fib(n-2)
```
I think the discrepancy in results is we are returning 1 if n <= 1 instead of returning 1 if n <= 2.

**Comment by drujensen** [comment]
> I tried examples in python 3, and found your calculations misleading as you took very bad example of recursion

@intha Why do you think this is a bad example for testing how a language handles recursive fib?

**Comment by drujensen** [comment]
All of the examples are using the same code so I think its a valid benchmark.  Closing this issue.

**Comment by francogrex** [comment]
This issue is a valid issue, the Readme should be rewritten to describe the actual mathematical function, because as it is, most examples who copied it ( return 1 if n <= 1) will give out wrong results.

**Comment by drujensen-happymoney** [comment]
It is written as a benchmark and it is using the traditional fib function.
