### ISSUE TITLE
HELP - Why did I get 21 PR's in one day?

### ISSUE THREAD

**Issue by drujensen** [drujensen/fib#51]
Can someone tell me why this project is all of the sudden very active?  21 PR's in one day.  I did this for a crystal presentation as a fun side project but I don't know if I can maintain it at this pace.

Does someone have time to help work on this?

**Comment by adamcarr1976** [comment]
The project is trending on HackerNews.

**Comment by OvermindDL1** [comment]
Heh, it might be good to build a testing apparatus (simple shell script) to start with so the tests become more easily run, along with testing the return value to make sure the code is correct (I think some of these aren't correct), then you can have travis run it against any PR's automatically so you can immediately reject and invalid ones to start with.

Also, your HN link:  https://news.ycombinator.com/item?id=18091655

**Comment by stevemk14ebr** [comment]
Here's a little tip: On this repos github page goto insights->traffic. At this page you can see where people come click through from, perfect for figuring this sort of thing out.

**Comment by OvermindDL1** [comment]
@drujensen  Accepted.  Is there anything specific you want me to do, just clean up and sort PR's or to start making simple shell script tests or so?

**Comment by OvermindDL1** [comment]
@stevemk14ebr  I didn't know about that, very cool!  Though it doesn't seem to list HackerNews on there?  Lot of other interesting places however.

**Comment by drujensen** [comment]
@OvermindDL1 thanks for your help!  Do you mind going through all the PR's and reviewing/accepting?

**Comment by drujensen** [comment]
Oh, also there are a lot of issues asking to change the flags for compilation, etc.  Can you update the readme with any requested changes?

**Comment by OvermindDL1** [comment]
Sure thing, I'll do so as I get time.  For any languages I don't know I'll see if I can compile/test them right quick first, if not I won't touch the PR if that's fine?

**Comment by OvermindDL1** [comment]
@drujensen Do you mind if I sort algorithms into directories, or at least put the non-exponential versions into their own directory to keep things separate?

**Comment by drujensen** [comment]
> Do you mind if I sort algorithms into directories, or at least put the non-exponential versions into their own directory to keep things separate?

No, please do.  thanks!

**Comment by drujensen** [comment]
> Heh, it might be good to build a testing apparatus (simple shell script) to start with so the tests become more easily run, along with testing the return value to make sure the code is correct (I think some of these aren't correct), then you can have travis run it against any PR's automatically so you can immediately reject any invalid ones to start with.

Would be cool if there was a docker image with all the languages installed.

**Comment by OvermindDL1** [comment]
> Would be cool if there was a docker image with all the languages installed.

I was actually considering using docker containers to build the projects.  I was going to start with just a Makefile for now, which can easily be extended to wrap docker calls later, but at the very least all of the calls to compile and run things needs to be in an easily executable location (which can of course be used by docker later).

**Comment by OvermindDL1** [comment]
What directory sorting do you think, `<algorithm-type>/<files>` or `<algorithm-type>/<language>/<files>` since some of them (`cs` for example) have multiple files for compilation since it has a csproj file (or should that even be there)?

**Comment by drujensen** [comment]
fortunately, the `csproj` is the only odd one so far.  I would do `<algorithm-type>/<files>` but I will let you decide.  If you find that the `cs` version makes this weird, you can add another directory.

**Comment by OvermindDL1** [comment]
I'm worried about what other languages may add.  Thankfully languages that require multi-file for something this trivial are not too, they do exist...  I'll leave it as just `<algorithm-type>/<files>` for now then.

**Comment by drujensen** [comment]
@OvermindDL1 FYI, I added a `run.sh` ruby script to run the main benchmarks and print the results.

**Comment by drujensen** [comment]
> Are you sure that's the 46th fib? And, you may consider testing iteratively as that would be much faster?
#37 says this is 47th not 46th fib.  Looks like your example confirms that. 

Regarding testing iteratively, The original focus was just recursive and my goal was to use as close of syntax as possible between the languages to keep the results apples to apples.  However, as you may have noticed, many are asking for memoization and other ways to compare. 

I personally feel the recursive version is a better benchmark since it requires more thought by the compiler to optimize.

**Comment by dbcfd** [comment]
> I personally feel the recursive version is a better benchmark since it requires more thought by the compiler to optimize.

Not necessarily. Different languages have differing levels of support for recursion, depending on whether the language views it as a primary method for writing implementations. They may make tradeoffs to support recursion by reducing performance in other areas or stack functionality.

**Comment by OvermindDL1** [comment]
I saw yep.

`constexpr` is so awesome, I use it extensively in C++.  ^.^

Elixir and clojure both have compile-time macro facilities that could also compile-time calculate `fib` as well.

Honestly, I think all the tests should be adjusted to take the integer on the program parameters or an environment variable or something.  That would both prevent such optimizations and would allow for easily CI'd consistency checks.  :-)

**Comment by drujensen** [comment]
> I think all the tests should be adjusted to take the integer on the program parameters or an environment variable or something.

Yeah, that was definitely a thought but it also adds a whole host of complexity between how languages handle `std::in`. Maybe its such a small exec time that it wouldn't effect the benchmark, not sure.

**Comment by OvermindDL1** [comment]
> Yeah, that was definitely a thought but it also adds a whole host of complexity between how languages handle std::in. Maybe its such a small exec time that it wouldn't effect the benchmark, not sure.

It's a useful thing to measure regardless.  A simple contract like passing `46` on the commandline as an argument, or perhaps passing `"46\n"` on stdin (slowest method) or `FIB=46 cmd ...` environment variable are all very common things so could be quite a good thing to add regardless.  But yeah, I don't think it would effect running time to anything really measureable.  Passing it as an argument or environment variable should be the universally 'fastest' among all languages.

**Comment by drujensen** [comment]
Ok, I opened a ticket #85  to track it.
