### ISSUE TITLE
Differences between C# and Java versions

### ISSUE THREAD

**Issue by marcin-chwedczuk** [drujensen/fib#61]
1. In C# you use `uint` type which is 4-byte, in Java you use `long` which is 8-byte integer type
2. Java version uses `System.out.print` which does NOT print new line at the end of the line, C# version uses `Console.WriteLine` which prints new line at the end
3. In C# code using `[MethodImpl(MethodImplOptions.AggressiveInlining)]` is questionable, first because using this attribute is not considered the best practice. Second because what will be done depends on runtime environment version.

**Comment by drujensen** [comment]
Good catch.  Can you provide updates to these examples?

**Comment by drujensen** [comment]
I was asked to include the `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to support TCO and was told it was needed to be a fair comparison to Java that uses it by default.  If that is not the case, you may remove it.

**Comment by OvermindDL1** [comment]
The oracle and openjdk java VM's do not support TCO at all.  There is no such thing as TCO in their ecosystems nor do they plan to add it (for the reason of 'it breaks stacktraces').

**Comment by OvermindDL1** [comment]
Commented there.

**Comment by drujensen** [comment]
I removed the `[MethodImpl(MethodImplOptions.AggressiveInlining)]` because it is an uncommon use of C#.  Closing this issue.
