### ISSUE TITLE
Using printf inside fib.c makes it unnecessary slow

### ISSUE THREAD

**Issue by marcin-chwedczuk** [drujensen/fib#63]
`clib` `printf` can be quite slow comparing to other methods of writing `long` to the `stdout`, this may be unfair when comparing with other languages that use printing routines optimized for int/longs (e.g. C# versions uses one). Please consider using `ultoa` and `puts` instead.

**Comment by drujensen** [comment]
sure, can you provide a PR with recommended changes?

**Comment by OvermindDL1** [comment]
@marcin-chwedczuk Can you do the same to the C++ example as it really should not be using locale-based streaming operations and should just use the same low level calls as C (in addition to changing the include)?

**Comment by drujensen** [comment]
I made the change to puts and updated the benchmarks.  Thanks!
