### ISSUE TITLE
Python: Another version

### ISSUE THREAD

**Issue by jdbctracer** [drujensen/fib#86]
Would it be possible to use a slightly different coding style?

```python
def fib(n):
    return 1 if n <= 1 else fib(n - 1) + fib(n - 2)
```
It makes a noticable difference on my machine without beeing much different from the original.

**Comment by drujensen** [comment]
Hi @jdbctracer I was trying to keep them all the same and use a guard instead of else condition. Both crystal and ruby versions are using the trailing `if`.

What about:
```
def fib(n):
    return 1 if n <= 1
    return fib(n - 1) + fib(n - 2)
```

**Comment by drujensen** [comment]
> It makes a noticeable difference on my machine

As in a performance difference?  I wonder why.  Seems like a guard would be just as fast.

**Comment by drujensen** [comment]
TIL `if then else` is faster than `if return` in python because it generates less opcodes.  Is this the case in other interpreted languages as well?

**Comment by OvermindDL1** [comment]
> Is this the case in other interpreted languages as well?

Not actually sure, python's the only opcode backend I've worked with so far aside from my own languages for interpreted languages (thus ignoring Java and so forth opcode work).

**Comment by jdbctracer** [comment]
For my small test the difference was around 9%.
I would guess that other languages could exhibit the same behaviour: 
  less opcodes -> more dense presentation of intent -> more optimized implementation
Keep in mind, that there is less infrastructure at runtime, no opcode rearrangement takes place.

**Comment by OvermindDL1** [comment]
@jdbctracer Precisely, but I wouldn't expect every language's opcode to be as 'high-level' as Python's is (which is pretty expressive for an opcode set), so others may not get quite as many boosts but I'd still expect a little.
