### ISSUE TITLE
Lisp Local is doing the same task

### ISSUE THREAD

**Issue by guicho271828** [drujensen/fib#88]
It is not breaking the benchmark, it is just helping the compiler to get the optimized code.

**Comment by drujensen** [comment]
ok.  I would prefer only one version for the regular benchmark that matches as close as possible to the other code examples. 

Do you want to replace the `fib.lisp` with `optimized/fib-local.lisp`?

**Comment by guicho271828** [comment]
I think I am fine if the description
> They do not perform the same internal tasks as the other examples
is changed to something like
> They do not have the syntactically equivalent code as the base examples. Some does not perform the same internal tasks as the other examples
and those that do the different internal tasks are marked as so.
by the way, I can contribute the memoized version of lisp too.

**Comment by drujensen** [comment]
aah, I see.  yeah, It's kinda strange having a 7s optimized version.  It really doesn't fit in the optimized category.  If you don't want to replace the primary benchmark with this, can we remove this example?  

>by the way, I can contribute the memoized version of lisp too.

It would be great to have a `fib-rem.lisp` example.

**Comment by drujensen** [comment]
I removed this so it didn't show up as 7 seconds in the optimized section.
