### ISSUE TITLE
Average time

### ISSUE THREAD

**Issue by VOID404** [drujensen/fib#96]
You are running calculation once in every language, and then one `time` per language. The result would be more reliable if it was averaged for multiple calculations, or just a sum of multiple calculation. A good example of it is optimised Nim and C++. In your benchmark Nim is twice as fast as C++, meanwhile by adding a 1'000'000 times loop, resulting difference is that C++ is 0.01s faster (with piping to /dev/null)
![benchmark](https://user-images.githubusercontent.com/9433601/52900642-913f3580-31f8-11e9-8797-0a78be7aff34.png)

**Comment by VOID404** [comment]
For clarity, here is what I mean
```cpp
#include <iostream>

constexpr uint32_t fib(uint32_t n) {
        if (n <= 1) return 1;
        return fib(n - 1) + fib(n - 2);
}

int main() {
        for (int i = 0; i < 1000000; i++) {
                std::cout << fib(46) << std::endl;
        }
        return 0;
}
```

**Comment by drujensen** [comment]
Added this along with compilation time.
