### ISSUE TITLE
Wrong value for 46th number in Fibonacci sequence in README.md

### ISSUE THREAD

**Issue by AmokHuginnsson** [drujensen/fib#99]
Fib(46) == 1836311903,
the value stated in README.md is for Fib(47).

**Comment by drujensen** [comment]
It depends on if the Fib sequence starts with a 0 or 1.  Both have been used.

https://stackoverflow.com/questions/1451170/in-the-fibonacci-sequence-is-fib0-0-or-1

**Comment by drujensen** [comment]
@AmokHuginnsson Thanks for opening this issue.  I added a note in the readme regarding which fibonacci sequence is being used.  That way I won't have to rewrite all the algorithms in 35 different languages. ;-)
